import streamlit as st
import pandas as pd
import plotly.graph_objects as go

from utils.data_loader import load_engineered_data, load_weather_cache, load_model
from utils.forecast import forecast_n_days, recent_history
from utils.theme import inject_theme, kicker

st.set_page_config(page_title="Forecast", page_icon="📈", layout="wide")
inject_theme()
kicker("01 · DEMAND FORECAST")
st.title("📈 Forecast")

feeder = st.session_state.get("selected_feeder")
address = st.session_state.get("selected_address")

if not feeder or not address:
    st.warning("No address selected yet. Go to the Home page and search for your address first.")
    st.page_link("app.py", label="\u2190 Back to Home")
    st.stop()

st.markdown(f"**{address}** — Feeder: *{feeder}*")

df = load_engineered_data()
weather = load_weather_cache()
model, features = load_model()

n_days = st.slider("Forecast horizon (days)", min_value=1, max_value=14, value=7)

with st.spinner("Generating forecast..."):
    try:
        forecast_df = forecast_n_days(df, weather, model, features, feeder, address, n_days=n_days)
    except ValueError as e:
        st.error(str(e))
        st.stop()

history_df = recent_history(df, feeder, address, n_days=30)

# ---------------------------------------------------------------------------
# Headline metrics
# ---------------------------------------------------------------------------
band = forecast_df["BAND"].iloc[0]
today_pred = forecast_df["PREDICTED_ACTUAL_HOURS"].iloc[0]
avg_pred = forecast_df["PREDICTED_ACTUAL_HOURS"].mean()
best_day = forecast_df.loc[forecast_df["PREDICTED_ACTUAL_HOURS"].idxmax()]
avg_shortfall = forecast_df["PREDICTED_SHORTFALL"].mean()
shortfall_frequency = (forecast_df["PREDICTED_SHORTFALL"] > 2).mean()

# stash for the Recommendations page so it doesn't need to recompute
st.session_state["avg_shortfall_hours"] = avg_shortfall
st.session_state["shortfall_frequency"] = shortfall_frequency
st.session_state["band"] = band

st.caption(
    f"This address is on a **{band:.0f}-hour band** -- the maximum electricity supply "
    f"it can be allocated per day, regardless of demand. All figures below are also "
    f"shown against this cap."
)

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Band (max hours/day)", f"{band:.0f}h")
col2.metric("Tomorrow's forecast", f"{today_pred:.1f}h")
col3.metric(f"{n_days}-day average", f"{avg_pred:.1f}h")
col4.metric("Best day", f"{best_day['PREDICTED_ACTUAL_HOURS']:.1f}h", help=str(best_day["DATE"]))
col5.metric("Avg. shortfall", f"{avg_shortfall:.1f}h", delta=f"of {band:.0f}h band", delta_color="off")

st.divider()

# ---------------------------------------------------------------------------
# Chart: recent actuals + forecast
# ---------------------------------------------------------------------------
st.subheader("Availability: recent history vs forecast")
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=history_df["DATE"], y=history_df["ACTUAL_HOURS"],
    mode="lines+markers", name="Actual (history)", line=dict(color="#1f77b4"),
))
fig.add_trace(go.Scatter(
    x=forecast_df["DATE"], y=forecast_df["PREDICTED_ACTUAL_HOURS"],
    mode="lines+markers", name="Predicted", line=dict(color="#ff7f0e", dash="dash"),
))
fig.add_hline(y=band, line_dash="dot", line_color="gray",
              annotation_text=f"Band cap ({band:.0f}h)", annotation_position="top left")
fig.update_layout(
    yaxis_title="Hours of electricity", xaxis_title="Date",
    yaxis_range=[0, 25], hovermode="x unified", legend=dict(orientation="h", y=1.1),
)
st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------------------------------
# Forecast table
# ---------------------------------------------------------------------------
st.subheader("Daily forecast detail")
display_df = forecast_df.rename(columns={
    "DATE": "Date", "PREDICTED_ACTUAL_HOURS": "Predicted hours",
    "BAND": "Band (h)",
    "PREDICTED_SHORTFALL": "Predicted shortfall (h)",
    "PREDICTED_AVAILABILITY_PCT": "Availability vs band %",
})
st.dataframe(
    display_df[["Date", "Predicted hours", "Band (h)", "Predicted shortfall (h)", "Availability vs band %"]],
    use_container_width=True, hide_index=True,
)

st.caption(
    "Forecast is generated by recursively applying a one-day-ahead model -- "
    "accuracy degrades the further out you look, especially past 3-4 days. "
    "Weather inputs are currently synthetic."
)
